#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

#
# Azure Pipeline specifically for building and publishing documentation
#

trigger:
- master
- docs

pool:
  vmImage: 'ubuntu-20.04'

steps:
  ## Fetch version number to ensure up-to-date cache
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    name: install_python
  - bash: |
      echo "###vso[task.setvariable variable=pip_cache;]${HOME}/.cache/pip"
      echo "###vso[task.setvariable variable=PATH;]$(python3 -m site --user-base)/bin:${PATH}"
      echo "###vso[task.setvariable variable=build_tool_options;]-j 4"
      sudo apt-get install -y clang-tools
    name: setup_linux
  - task: Cache@2
    inputs:
      key: pip | 2 | $(Agent.OS)
      path: $(pip_cache)
    name: cache_pip
  - bash: |
      set -e -x
      pip install sphinx breathe --user
    name: install_sphinx
  - bash: |
      set -e -x
      mkdir build
      cd build
      cmake -DBUILD_DOCS=on -DBUILD_IDLC=off ..
      cmake --build .
    name: 'Build documentation'
  - script: |
      set -e -x
      cd build/docs/docs
      git init
      git config --local user.name "Azure Pipelines"
      git config --local user.email "azuredevops@microsoft.com"
      git add .
      git commit -m "Publishing GitHub Pages  ***NO_CI***"
    name: 'Commit pages'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: deploy_key
    name: 'Get the deploy key'

  - script: |
      mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote set-url --push origin git@github.com:thijsmie/cyclonedds.github.io.git
      git push -f origin HEAD:master
    displayName: 'Publish GitHub Pages'