#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

#
# Azure Pipeline specifically for building and publishing documentation
#

trigger:
- master
- docs

pool:
  name: 'Default'


steps:
  ## Fetch version number to ensure up-to-date cache
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    name: install_python
  - bash: |
      echo "###vso[task.setvariable variable=pip_cache;]${HOME}/.cache/pip"
      echo "###vso[task.setvariable variable=PATH;]$(python3 -m site --user-base)/bin:${PATH}"
      echo "###vso[task.setvariable variable=build_tool_options;]-j 4"
      sudo apt-get install -y clang-tools
    name: setup_linux
  - task: Cache@2
    inputs:
      key: pip | 2 | $(Agent.OS)
      path: $(pip_cache)
    name: cache_pip
  - task: Cache@2
    inputs:
      key: conan | 3 | $(Agent.OS) | Documentation
      path: $(conan_cache)
    name: cache_conan
  - bash: |
      set -e -x
      pip install conan --user
      conan profile new default --detect || true
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || true
    name: install_conan
  - bash: |
      set -e -x
      pip install sphinx breathe --user
    name: install_sphinx
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCmRjbIQqtoN+t9xjFZ5RqPQlwcgk784i1VPcGvYQoVFw440qCRbHvbdPd0IjHn9DzawK4qem6RtqbOkVBLVS4GWuqOuHHvGrPDVxuXp1DGe/CtzWYvChx/UGUC83iQn/w8nEQQGgmOk4sYJmEg105UlweoKn15zjHJqJ6tVzQS7pNQZCsWmrk6OHBsz05bS0VjO6h/p7WOb7PRHi0G+efc74FDI7MOzvRFf3PKxmjjmxxrssx96Fx5kzMzrIlQdxlyGTLkzK3JL1gaLro9ykHnbwGMkup1eJ7ckOi5Ke+kye6+Gziopq4KQMxNqKy/2qAaK6xeo10Jn6DtlfafXv9
      sshKeySecureFile: deploy_key
    name: 'get_deploy_key'
  - bash: |
      set -e -x
      mkdir -p build/docs
      cd build/docs
      git config --local user.name "Azure Pipelines"
      git config --local user.email "azuredevops@microsoft.com"
      git clone git@github.com:thijsmie/cddstemp.github.io.git docs
    name: prepare_build_git
  - bash: |
      set -e -x
      cd build
      conan install -b missing -s arch=x86_64 -s build_type=Debug ../conanfile-documentation.txt
      cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=on -DBUILD_IDLC=off ..
      cmake --build .
      cd ..
    name: 'build_documentation'
  - script: |
      set -e -x
      cd build/docs/docs
      touch .nojekyll
      git add .
      git commit -m "Publishing GitHub Pages $(Build.SourceVersion) ***NO_CI***"
      git push -f origin HEAD:master
    name: 'commit_pages'
